export {
  calcularDerivadaQuadratica,
  classifyVariation,
  evaluateDerivative,
  formatDerivative,
  variationLabel,
} from "./derivative";
export {
  ANGLE_MAX,
  ANGLE_MIN,
  ANGLE_VALID_MAX,
  ANGLE_VALID_MIN,
  FORCE_MAX,
  FORCE_MIN,
  FORCE_VALID_MAX,
  FORCE_VALID_MIN,
  GRAVITY,
  HIT_RADIUS,
  MAX_SPEED,
  MIN_SPEED,
  checkHoop,
  evaluateQuadratic,
  formatFunction,
  gerarTrajetoria,
  parabolaCoefficients,
  quadraticRoots,
  speedFromForce,
  validateShotInputs,
  velocityFromShot,
} from "./trajectory";
export type {
  CriticalClassification,
  GerarTrajetoriaInput,
  HoopCheck,
  Linear,
  Point,
  Quadratic,
  TrajectoryAnalysis,
  TrajectoryResult,
  VariationRate,
  Velocity,
} from "./types";
export {
  calcularVertice,
  classificationLabel,
  classificationReason,
  classificarPontoCritico,
  segundaDerivada,
} from "./vertex";
